[package]
name = "trm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
lscolors = {version = "0.20.0", features = ["crossterm"]}
nu-ansi-term = "0.50.1"
chrono = "0.4.39"
uutils_term_grid = "0.6.0"
terminal_size = "0.4.1"
